# Generated by Django 5.2.9 on 2025-12-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='xp_for_next_lvl',
            field=models.IntegerField(default=100, verbose_name='XP для следующего уровня'),
        ),
    ]
