# Generated by Django 5.2.9 on 2025-12-18 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_xp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='level',
        ),
    ]
