# Generated by Django 5.2.9 on 2025-12-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название')),
                ('description', models.TextField(max_length=500, verbose_name='описание')),
                ('status', models.CharField(choices=[('done', 'Выполнено'), ('in_progress', 'В процессе выполнения'), ('not_started', 'Не приступал к выполнению')], default='not_started', max_length=20, verbose_name='Статус')),
                ('start_date', models.DateField(verbose_name='дата начала')),
                ('end_date', models.DateField(verbose_name='дата окончания')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
