# Generated by Django 5.2.9 on 2025-12-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата окончания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(auto_now_add=True, verbose_name='дата начала'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('not_started', 'Не приступал к выполнению'), ('in_progress', 'В процессе выполнения'), ('done', 'Выполнено')], default='not_started', max_length=20, verbose_name='Статус'),
        ),
    ]
