# Generated by Django 5.2.9 on 2025-12-18 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_description_alter_task_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='start_date',
            new_name='created_at',
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название')),
                ('status', models.CharField(choices=[('not_started', 'Не приступал к выполнению'), ('in_progress', 'В процессе выполнения'), ('done', 'Выполнено')], default='not_started', max_length=20, verbose_name='cтатус')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='подзадача', to='tasks.task')),
            ],
            options={
                'verbose_name': 'Подзадача',
                'verbose_name_plural': 'Подзадачи',
            },
        ),
    ]
