# Generated by Django 5.2.9 on 2025-12-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('in_progress', 'В процессе'), ('done', 'Выполнено')], default='in_progress', max_length=20, verbose_name='cтатус'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата начала'),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата окончания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('in_progress', 'В процессе'), ('done', 'Выполнено')], default='in_progress', max_length=20, verbose_name='Статус'),
        ),
    ]
